# Generated by Django 4.1.7 on 2023-03-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='testcase',
            field=models.JSONField(default=dict, verbose_name='테스트케이스'),
        ),
    ]
